# Generated by Django 4.2.5 on 2023-09-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_programmer_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Fecha_de_registro', models.DateTimeField()),
                ('Autor', models.CharField(max_length=100)),
                ('Precio', models.CharField(max_length=100)),
                ('Editorial', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Programmer',
        ),
    ]
