# Generated by Django 4.2.5 on 2023-09-10 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_libros_delete_programmer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Libros',
            new_name='Libro',
        ),
    ]
