# Generated by Django 4.2.5 on 2023-09-10 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_libros_libro'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Libro',
            new_name='Libros',
        ),
    ]
